version: '3.8'

services:
  discovery-service:
    build:
      context: ./eureka
    container_name: ${DISCOVERY_NAME}
    ports:
      - "${DISCOVERY_PORT}:${DISCOVERY_PORT}"
    networks:
      - spring-cloud
    environment:
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false

  product-service:
    build:
      context: ./product
    container_name: ${PRODUCT_ID}
    ports:
      - "${PRODUCT_PORT}:${PRODUCT_PORT}"
    depends_on:
      - discovery-service
    networks:
      - spring-cloud
    environment:
      - SPRING_APPLICATION_NAME=${PRODUCT_NAME}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${DISCOVERY_URL}
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - JWT_SECRET=${SECRET}
    restart: always

  auth-service:
    build:
      context: ./auth
    container_name: ${AUTH_ID}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      - discovery-service
    networks:
      - spring-cloud
    environment:
      - SPRING_APPLICATION_NAME=${AUTH_NAME}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${DISCOVERY_URL}
      - JWT_SECRET=${SECRET}
    restart: always

  api-gateway:
    build:
      context: ./gateway
    container_name: ${GATEWAY_NAME}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - auth-service
      - product-service
    networks:
      - spring-cloud
    environment:
      - SPRING_APPLICATION_NAME=${GATEWAY_NAME}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${DISCOVERY_URL}
      - JWT_SECRET=${SECRET}
    restart: always

networks:
  spring-cloud:
    driver: bridge
