server:
  port: ${PORT:8080} # use $PORT if set, fallback to 8761 locally

spring:
  application:
    name: product-service
#http://localhost:8761/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-service-8vz8.onrender.com/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.gateway: DEBUG