server:
  port: ${PORT:${PRODUCT_PORT}}

spring:
  application:
    name: ${PRODUCT_NAME}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVER_URL}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.netflix.discovery: DEBUG
