server:
  port: ${PORT:${PRODUCT_PORT}}

spring:
  application:
    name: ${PRODUCT_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVER_URL}
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: ${PRODUCT_HOST}
    prefer-ip-address: false
    non-secure-port: ${PRODUCT_PORT}
    instance-id: ${PRODUCT_HOST}:${PRODUCT_PORT}
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.netflix.discovery: DEBUG


#  instance:
#    hostname: your-product-service.onrender.com  # 👈 Your actual Render subdomain
#    prefer-ip-address: false
#    instance-id: your-product-service.onrender.com:${server.port}
#    non-secure-port-enabled: false     # Prevent Eureka from setting HTTP port
#    secure-port-enabled: true
#    secure-port: 443
#    status-page-url: https://your-product-service.onrender.com/actuator/info
#    home-page-url: https://your-product-service.onrender.com
#    health-check-url: https://your-product-service.onrender.com/actuator/health