server:
  port: ${PORT:${GATEWAY_PORT}}

spring:
  application:
    name: ${GATEWAY_NAME}

  cloud:
    gateway:
      routes:
        - id: ${AUTH_ID}
          uri: ${AUTH_URI}
          predicates:
            - Path=${AUTH_PATH}
        - id: ${PRODUCT_ID}
          uri: ${PRODUCT_URI}
          predicates:
            - Path=${PRODUCT_PATH}
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVER_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${GATEWAY_HOST}
    prefer-ip-address: false
    non-secure-port: ${GATEWAY_PORT}
    instance-id: ${GATEWAY_HOST}:${GATEWAY_PORT}
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.gateway: DEBUG
