server:
  port: ${PORT:${AUTH_PORT}}

spring:
  application:
    name: auth-service
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://accounts.google.com
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${AUTH_HOST}
    prefer-ip-address: false
    non-secure-port: ${AUTH_PORT}
    instance-id: ${AUTH_HOST}:${AUTH_PORT}
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}

jwt:
  secret: ${SECRET}
